updates

diff --git a/shopwise/Dockerfile b/shopwise/Dockerfile
--- a/shopwise/Dockerfile
+++ b/shopwise/Dockerfile
@@ -1,127 +1,82 @@
-FROM amazonlinux:2
+FROM amazonlinux:2023
 
 # Update all installed packages to their latest versions
-RUN yum update -y 
+RUN dnf update -y 
 
-# Install the unzip package, which we will use it to extract the web files from the zip folder
-RUN yum install -y unzip
+# Install required packages
+RUN dnf install -y unzip wget httpd git
 
-# Install wget package, which we will use it to download files from the internet 
-RUN yum install -y wget
+# Enable and install PHP with extensions
+RUN dnf install -y php php-common php-pear php-cgi php-curl php-mbstring \
+    php-gd php-mysqlnd php-gettext php-json php-xml php-fpm php-intl php-zip
 
-# Install Apache
-RUN yum install -y httpd
+# Install MySQL client and community server
+RUN wget https://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm && \
+    rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023 && \
+    dnf localinstall -y mysql80-community-release-el7-3.noarch.rpm && \
+    dnf install -y mysql-community-server
 
-# Install PHP and various extensions
-RUN amazon-linux-extras enable php7.4 && \
-  yum clean metadata && \
-  yum install -y \
-    php \
-    php-common \
-    php-pear \
-    php-cgi \
-    php-curl \
-    php-mbstring \
-    php-gd \
-    php-mysqlnd \
-    php-gettext \
-    php-json \
-    php-xml \
-    php-fpm \
-    php-intl \
-    php-zip
-
-# Download the MySQL repository package
-RUN wget https://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm
-
-# Import the GPG key for the MySQL repository
-RUN rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
-
-# Install the MySQL repository package
-RUN yum localinstall mysql80-community-release-el7-3.noarch.rpm -y
-
-# Install the MySQL community server package
-RUN yum install mysql-community-server -y
-
-# Change directory to the html directory
+# Set the working directory
 WORKDIR /var/www/html
 
-# Install Git
-RUN yum install -y git
-
-# Set the build argument directive
+# Set the build arguments
 ARG PERSONAL_ACCESS_TOKEN
 ARG GITHUB_USERNAME
 ARG REPOSITORY_NAME
 ARG WEB_FILE_ZIP
-ARG WEB_FILE_UNZIP
 ARG DOMAIN_NAME
 ARG RDS_ENDPOINT
 ARG RDS_DB_NAME
 ARG RDS_DB_USERNAME
 ARG RDS_DB_PASSWORD
 
-# Use the build argument to set environment variables 
-ENV PERSONAL_ACCESS_TOKEN=$PERSONAL_ACCESS_TOKEN 
-ENV GITHUB_USERNAME=$GITHUB_USERNAME
-ENV REPOSITORY_NAME=$REPOSITORY_NAME
-ENV WEB_FILE_ZIP=$WEB_FILE_ZIP
-ENV WEB_FILE_UNZIP=$WEB_FILE_UNZIP
-ENV DOMAIN_NAME=$DOMAIN_NAME
-ENV RDS_ENDPOINT=$RDS_ENDPOINT
-ENV RDS_DB_NAME=$RDS_DB_NAME
-ENV RDS_DB_USERNAME=$RDS_DB_USERNAME
-ENV RDS_DB_PASSWORD=$RDS_DB_PASSWORD
+# Set environment variables based on build arguments
+ENV PERSONAL_ACCESS_TOKEN=$PERSONAL_ACCESS_TOKEN \
+    GITHUB_USERNAME=$GITHUB_USERNAME \
+    REPOSITORY_NAME=$REPOSITORY_NAME \
+    WEB_FILE_ZIP=$WEB_FILE_ZIP \
+    DOMAIN_NAME=$DOMAIN_NAME \
+    RDS_ENDPOINT=$RDS_ENDPOINT \
+    RDS_DB_NAME=$RDS_DB_NAME \
+    RDS_DB_USERNAME=$RDS_DB_USERNAME \
+    RDS_DB_PASSWORD=$RDS_DB_PASSWORD
 
 # Clone the GitHub repository
 RUN git clone https://${PERSONAL_ACCESS_TOKEN}@github.com/${GITHUB_USERNAME}/${REPOSITORY_NAME}.git
 
-# Unzip the zip folder containing the web files
-RUN unzip ${REPOSITORY_NAME}/${WEB_FILE_ZIP} -d ${REPOSITORY_NAME}/
+# Verify if the zip file exists and unzip, if it doesn’t exist, print an error message
+RUN if [ -f "${REPOSITORY_NAME}/${WEB_FILE_ZIP}" ]; then \
+        unzip ${REPOSITORY_NAME}/${WEB_FILE_ZIP} -d ${REPOSITORY_NAME}/; \
+    else \
+        echo "Error: ${WEB_FILE_ZIP} not found in ${REPOSITORY_NAME}"; \
+        exit 1; \
+    fi
 
-# Copy the web files into the HTML directory
-RUN cp -av ${REPOSITORY_NAME}/. /var/www/html
+# Copy web files to the HTML directory and clean up
+RUN cp -av ${REPOSITORY_NAME}/. /var/www/html && rm -rf ${REPOSITORY_NAME}
 
-# Remove the repository we cloned
-RUN rm -rf ${REPOSITORY_NAME}
-
-# Enable the mod_rewrite setting in the httpd.conf file
+# Configure Apache settings
 RUN sed -i '/<Directory "\/var\/www\/html">/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/httpd/conf/httpd.conf
 
-# Give full access to the /var/www/html directory
-RUN chmod -R 777 /var/www/html
+# Update permissions
+RUN chmod -R 777 /var/www/html && chmod -R 777 /var/www/html/storage
 
-# Give full access to the storage directory
-RUN chmod -R 777 storage/
+# Update environment variables in .env file
+RUN sed -i "/^APP_ENV=/ s/=.*$/=production/" .env && \
+    sed -i "/^APP_URL=/ s/=.*$/=https:\/\/${DOMAIN_NAME}\//" .env && \
+    sed -i "/^DB_HOST=/ s/=.*$/=${RDS_ENDPOINT}/" .env && \
+    sed -i "/^DB_DATABASE=/ s/=.*$/=${RDS_DB_NAME}/" .env && \
+    sed -i "/^DB_USERNAME=/ s/=.*$/=${RDS_DB_USERNAME}/" .env && \
+    sed -i "/^DB_PASSWORD=/ s/=.*$/=${RDS_DB_PASSWORD}/" .env
 
-# Use the sed command to search the .env file for a line that starts with APP_ENV= and replace everything after the = character
-RUN sed -i '/^APP_ENV=/ s/=.*$/=production/' .env
-
-# Use the sed command to search the .env file for a line that starts with APP_URL= and replace everything after the = character
-RUN sed -i "/^APP_URL=/ s/=.*$/=https:\/\/${DOMAIN_NAME}\//" .env
-
-# Use the sed command to search the .env file for a line that starts with DB_HOST= and replace everything after the = character
-RUN sed -i "/^DB_HOST=/ s/=.*$/=${RDS_ENDPOINT}/" .env
-
-# Use the sed command to search the .env file for a line that starts with DB_DATABASE= and replace everything after the = character
-RUN sed -i "/^DB_DATABASE=/ s/=.*$/=${RDS_DB_NAME}/" .env
-
-# Use the sed command to search the .env file for a line that starts with DB_USERNAME= and replace everything after the = character
-RUN  sed -i "/^DB_USERNAME=/ s/=.*$/=${RDS_DB_USERNAME}/" .env
-
-# Use the sed command to search the .env file for a line that starts with DB_PASSWORD= and replace everything after the = character
-RUN  sed -i "/^DB_PASSWORD=/ s/=.*$/=${RDS_DB_PASSWORD}/" .env
-
-# Print the .env file to review values
+# Display the .env file for verification
 RUN cat .env
 
-# Copy the file, AppServiceProvider.php from the host file system into the container at the path app/Providers/AppServiceProvider.php
+# Copy AppServiceProvider.php to container
 COPY AppServiceProvider.php app/Providers/AppServiceProvider.php
 
-# Expose the default Apache and MySQL ports
+# Expose required ports
 EXPOSE 80 3306
 
-# Start Apache and MySQL
+# Start Apache in the foreground
 ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]
-
-##
